services:
  database:
    image: postgres:17.3
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=checkout-db
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]

volumes:
  db: