services:
  checkout:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    image: dedicated-instance-image
    environment:
      - SERVICE=api
      - DB_HOST=database
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ~/.aws:/root/.aws
    working_dir: /app
    depends_on:
      - "database"
    configs:
      - source: configfile
        target: /app/config.yaml
  database:
    image: postgres:17.3
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=checkout-inventory
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]

volumes:
  db: