// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ATMackay/checkout/services/orders (interfaces: Relayer)
//
// Generated by this command:
//
//	mockgen -destination mock/relay.go -package mock github.com/ATMackay/checkout/services/orders Relayer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRelayer is a mock of Relayer interface.
type MockRelayer struct {
	ctrl     *gomock.Controller
	recorder *MockRelayerMockRecorder
	isgomock struct{}
}

// MockRelayerMockRecorder is the mock recorder for MockRelayer.
type MockRelayerMockRecorder struct {
	mock *MockRelayer
}

// NewMockRelayer creates a new mock instance.
func NewMockRelayer(ctrl *gomock.Controller) *MockRelayer {
	mock := &MockRelayer{ctrl: ctrl}
	mock.recorder = &MockRelayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayer) EXPECT() *MockRelayerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockRelayer) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRelayerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRelayer)(nil).Ping), ctx)
}

// Start mocks base method.
func (m *MockRelayer) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRelayerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRelayer)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockRelayer) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRelayerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRelayer)(nil).Stop))
}
