# Alex Mackay 2025
# Golang CI with GitHub Actions
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.1'

    - name: build
      run: go build -v ./...

    - name: unit-test
      run: go test -v ./...

  golangci:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: goinstall
          version: latest
          args: --timeout=2m

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.1'

    - name: run integration tests
      run: make test-integration
